#version 450

#extension GL_GOOGLE_include_directive: require

#include "include/Math.iglsl"
#include "include/Mesh.iglsl"
#include "include/Lights.iglsl"

struct UniformGrid
{
    vec4 max;
    vec4 min;
	uint numberOfDivisions;
    uint indirectDrawCount;
};

layout(push_constant) uniform GlobalContext 
{
    UniformGrid grid;    
} gs;

layout(set = 0, binding = 0) writeonly buffer Commands 
{
	IndexedIndirectCommand commands[];
} cmdBuffer;

layout(set = 0, binding = 1) buffer PMBuffer 
{
    MeshDetails objects[];
} perModelBuffer;

layout(set = 0, binding = 2) uniform CameraData 
{
     mat4 view;
     mat4 proj;
     Frustum f;
     mat4 world;
} cData;

layout(set = 0, binding = 3, r32ui) uniform uimageBuffer globalRenderableIndices;

layout(set = 0, binding = 4) writeonly buffer commandCounts 
{
    uint visibleCount;
    uint invisibleCount;
} cCounts;

layout(set = 0, binding = 5) buffer RENDBuffer
{
    MeshRenderable renderables[];
} rends;

layout(set = 0, binding = 6) readonly buffer GeomDescBuffer
{
    GeometryDetails details[];
} geomDetails;

layout(set = 0, binding = 7) readonly buffer GeomInstBuffer
{
    GeometryRenderable geomRenderables[];
} geomRends;

layout(set = 1, binding = 0) uniform usamplerBuffer globalLightOffsets;
layout(set = 1, binding = 1) uniform usamplerBuffer globalLightCounts;
layout(set = 1, binding = 2) uniform usamplerBuffer globalLightAllocations;

layout(set = 1, binding = 3) readonly buffer GLBuffer 
{
    LightSource objects[];
} lightBuffer;

layout(set = 1, binding = 4) uniform usamplerBuffer globalLightTypes;

Frustum CalculateFrustrum()
{
    Frustum transformFrustrum;
    transformFrustrum.nearplane = TransformPlane(cData.world, cData.f.nearplane);
    transformFrustrum.farplane = TransformPlane(cData.world, cData.f.farplane);
    transformFrustrum.topplane = TransformPlane(cData.world, cData.f.topplane);
    transformFrustrum.bottomplane = TransformPlane(cData.world, cData.f.bottomplane);
    transformFrustrum.rightplane = TransformPlane(cData.world, cData.f.rightplane);
    transformFrustrum.leftplane = TransformPlane(cData.world, cData.f.leftplane);
    return transformFrustrum;
}

bool CheckAllPlanesAgainstAABB(AABB inputAABB, mat4 worldMatrix)
{
    AABB outAABBTransform = TransformAABBArvo(worldMatrix, inputAABB);

    vec4 transAABBMin =  outAABBTransform.min;
    vec4 transAABBMax =  outAABBTransform.max;

    vec4 AABBMin = min(transAABBMin, transAABBMax);
    vec4 AABBMax = max(transAABBMin, transAABBMax);

    Frustum testFrustrum = CalculateFrustrum();

    bool check = CheckAABB(AABBMin, AABBMax, testFrustrum.nearplane.planeEquation);

    if (!check)
    {
        return false;
    }

    check = CheckAABB(AABBMin, AABBMax, testFrustrum.farplane.planeEquation);

    if (!check)
    {
        return false;
    }
    
    check = CheckAABB(AABBMin, AABBMax, testFrustrum.topplane.planeEquation);

    if (!check)
    {
        return false;
    }
    
    check = CheckAABB(AABBMin, AABBMax, testFrustrum.bottomplane.planeEquation);

    if (!check)
    {
        return false;
    }
    
    
    check = CheckAABB(AABBMin, AABBMax, testFrustrum.rightplane.planeEquation);

    if (!check)
    {
        return false;
    }
    
    check = CheckAABB(AABBMin, AABBMax, testFrustrum.leftplane.planeEquation);

    if (!check)
    {
        return false;
    }
    
    return true;
}

bool CheckAllPlanesAgainstSphere(mat4 worldMatrix, vec4 inSphere)
{
    float r = inSphere.w;

    vec3 transPosition =  vec3(worldMatrix * vec4(inSphere.xyz, 1.0));

    Frustum testFrustrum = CalculateFrustrum();

   float dist = DistanceFromPlane(testFrustrum.nearplane.planeEquation, transPosition);

    if (dist < -r)
    {
        return false;
    }

    dist = DistanceFromPlane(testFrustrum.farplane.planeEquation, transPosition);

    if (dist < -r)
    {
        return false;
    }
    
    dist = DistanceFromPlane(testFrustrum.topplane.planeEquation, transPosition);

    if (dist < -r)
    {
        return false;
    }
    
    dist = DistanceFromPlane(testFrustrum.bottomplane.planeEquation, transPosition);

    if (dist < -r)
    {
        return false;
    }
     
    dist = DistanceFromPlane(testFrustrum.rightplane.planeEquation, transPosition);

    if (dist < -r)
    {
        return false;
    }
    
    dist = DistanceFromPlane(testFrustrum.leftplane.planeEquation, transPosition);

    if (dist < -r)
    {
        return false;
    }

    return true;
    
}

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

void main()
{
	uint index = (gl_WorkGroupID.x * gl_WorkGroupSize.x) + gl_LocalInvocationID.x;

    uint maxCount = gs.grid.indirectDrawCount;
  
    if (index >= maxCount)  
    {
        return;
    }

    MeshRenderable currentRenderable = rends.renderables[index];

    GeometryRenderable lGeomRenderable = geomRends.geomRenderables[currentRenderable.geomInstIndex];

    GeometryDetails lGeomDetails = geomDetails.details[lGeomRenderable.geomDescIndex];

    MeshDetails lModelData = perModelBuffer.objects[currentRenderable.meshIndex];

    mat4 worldM = lGeomRenderable.transform * currentRenderable.transform;

    vec4 sphere = lModelData.sphere;

    bool visible = CheckAllPlanesAgainstAABB(lGeomDetails.minMaxBox, worldM);

    if (!visible)
    {
        uint invisibleIndex = atomicAdd(cCounts.invisibleCount, 1u);
        cmdBuffer.commands[maxCount-(1+invisibleIndex)].instanceCount = 0;
        return;
    } 

    uint visibleIndex = atomicAdd(cCounts.visibleCount, 1u);
   
    imageStore(globalRenderableIndices, int(visibleIndex), uvec4(index, 0, 0, 0));

    cmdBuffer.commands[visibleIndex].instanceCount = currentRenderable.instanceCount;
    cmdBuffer.commands[visibleIndex].firstIndex = lModelData.firstIndex;
    cmdBuffer.commands[visibleIndex].indexCount = lModelData.indexCount;
    cmdBuffer.commands[visibleIndex].firstInstance = 0;
    cmdBuffer.commands[visibleIndex].vertexOffset = 0;
   
    float r = sphere.w;

    vec3 sphereWPos = vec3(worldM * vec4(sphere.xyz, 1.0f));

    vec4 range = gs.grid.max - gs.grid.min;
    vec3 cellDiv = range.xyz / float(gs.grid.numberOfDivisions);

    vec3 posRelativeToGrid = sphereWPos-gs.grid.min.xyz;

    ivec3 cells = ivec3(floor(posRelativeToGrid / cellDiv));

    uint worldIndex = (cells.x * gs.grid.numberOfDivisions * gs.grid.numberOfDivisions) + (cells.y * gs.grid.numberOfDivisions) + cells.z;
    
    uint lightOffsets =  texelFetch(globalLightOffsets, int(worldIndex)).r;
    uint lightCounts =  texelFetch(globalLightCounts, int(worldIndex)).r;

    uint dc = GET_LIGHT_TYPE_DIRECTIONAL_COUNT(lightCounts);
    uint poc = GET_LIGHT_TYPE_POINT_COUNT(lightCounts);
    uint sc = GET_LIGHT_TYPE_SPOT_COUNT(lightCounts);

    lightCounts = sc + poc + dc;

    uint lightMeshCount = 0;

    for (uint i = 0; i<lightCounts&&lightMeshCount<4; i++)
    {
        uint lightIndex = texelFetch(globalLightAllocations, int(lightOffsets+i)).r;

        uint lType = uint(texelFetch(globalLightTypes, int(lightIndex)).r);

        if (lType == LIGHT_TYPE_DIRECTIONAL)
        {
            rends.renderables[index].lightIndices[lightMeshCount] = lightIndex;
            lightMeshCount++;
        }
        else if (lType == LIGHT_TYPE_POINT)
        {
            vec4 posLoad = lightBuffer.objects[lightIndex].pos;

            float lR = posLoad.w;
            vec3 posTest = posLoad.xyz;

            posTest = sphereWPos - posTest;

            float totalRadius = lR + r;

            float d = dot(posTest, posTest);

            if (d <= totalRadius * totalRadius)
            {
                rends.renderables[index].lightIndices[lightMeshCount] = lightIndex;
                lightMeshCount++;
            }
        }
        else if (lType == LIGHT_TYPE_SPOT)
        {
            vec4 posLoad = lightBuffer.objects[lightIndex].pos;
            vec3 dirLoad = lightBuffer.objects[lightIndex].direction.xyz;

            bool addToLights = ConeIntersectSphere(posLoad.xyz, dirLoad, sphereWPos, r, posLoad.w, lightBuffer.objects[lightIndex].ancillary.y);

            if (addToLights)
            {
                rends.renderables[index].lightIndices[lightMeshCount] = lightIndex;
                lightMeshCount++;
            }
        }
    }

    rends.renderables[index].lightCount = lightMeshCount;
}
