#version 450

#extension GL_GOOGLE_include_directive: require

#include "include/Math.iglsl"
#include "include/Mesh.iglsl"
#include "include/Lights.iglsl"

struct UniformGrid
{
    vec4 max;
    vec4 min;
	uint numberOfDivisions;
    uint indirectDrawCount;
};

layout(push_constant) uniform GlobalContext 
{
    UniformGrid grid;    
} gs;

layout(set = 0, binding = 0) writeonly buffer Commands 
{
	IndexedIndirectCommand commands[];
} cmdBuffer;

layout(set = 0, binding = 1) buffer PMBuffer 
{
    MeshDetails objects[];
} perModelBuffer;

layout(set = 0, binding = 2) uniform CameraData 
{
     mat4 view;
     mat4 proj;
     Frustum f;
     mat4 world;
} cData;

layout(set = 0, binding = 3, r32ui) uniform uimageBuffer globalRenderableIndices;

layout(set = 0, binding = 4) writeonly buffer commandCounts 
{
    uint visibleCount;
    uint invisibleCount;
} cCounts;

layout(set = 0, binding = 5) buffer RENDBuffer
{
    MeshRenderable renderables[];
} rends;

layout(set = 0, binding = 6) readonly buffer GeomDescBuffer
{
    GeometryDetails details[];
} geomDetails;

layout(set = 0, binding = 7) readonly buffer GeomInstBuffer
{
    GeometryRenderable geomRenderables[];
} geomRends;

Frustum CalculateFrustrum()
{
    Frustum transformFrustrum;
    transformFrustrum.nearplane = TransformPlane(cData.world, cData.f.nearplane);
    transformFrustrum.farplane = TransformPlane(cData.world, cData.f.farplane);
    transformFrustrum.topplane = TransformPlane(cData.world, cData.f.topplane);
    transformFrustrum.bottomplane = TransformPlane(cData.world, cData.f.bottomplane);
    transformFrustrum.rightplane = TransformPlane(cData.world, cData.f.rightplane);
    transformFrustrum.leftplane = TransformPlane(cData.world, cData.f.leftplane);
    return transformFrustrum;
}

bool CheckAllPlanesAgainstAABB(AABB inputAABB, mat4 worldMatrix)
{
    AABB outAABBTransform = TransformAABBArvo(worldMatrix, inputAABB);

    vec4 transAABBMin =  outAABBTransform.min;
    vec4 transAABBMax =  outAABBTransform.max;

    vec4 AABBMin = min(transAABBMin, transAABBMax);
    vec4 AABBMax = max(transAABBMin, transAABBMax);

    Frustum testFrustrum = CalculateFrustrum();

    bool check = CheckAABB(AABBMin, AABBMax, testFrustrum.nearplane.planeEquation);

    if (!check)
    {
        return false;
    }

    check = CheckAABB(AABBMin, AABBMax, testFrustrum.farplane.planeEquation);

    if (!check)
    {
        return false;
    }
    
    check = CheckAABB(AABBMin, AABBMax, testFrustrum.topplane.planeEquation);

    if (!check)
    {
        return false;
    }
    
    check = CheckAABB(AABBMin, AABBMax, testFrustrum.bottomplane.planeEquation);

    if (!check)
    {
        return false;
    }
    
    
    check = CheckAABB(AABBMin, AABBMax, testFrustrum.rightplane.planeEquation);

    if (!check)
    {
        return false;
    }
    
    check = CheckAABB(AABBMin, AABBMax, testFrustrum.leftplane.planeEquation);

    if (!check)
    {
        return false;
    }
    
    return true;
}

bool CheckAllPlanesAgainstSphere(mat4 worldMatrix, vec4 inSphere)
{
    float r = inSphere.w;

    vec3 transPosition =  vec3(worldMatrix * vec4(inSphere.xyz, 1.0));

    Frustum testFrustrum = CalculateFrustrum();

   float dist = DistanceFromPlane(testFrustrum.nearplane.planeEquation, transPosition);

    if (dist < -r)
    {
        return false;
    }

    dist = DistanceFromPlane(testFrustrum.farplane.planeEquation, transPosition);

    if (dist < -r)
    {
        return false;
    }
    
    dist = DistanceFromPlane(testFrustrum.topplane.planeEquation, transPosition);

    if (dist < -r)
    {
        return false;
    }
    
    dist = DistanceFromPlane(testFrustrum.bottomplane.planeEquation, transPosition);

    if (dist < -r)
    {
        return false;
    }
     
    dist = DistanceFromPlane(testFrustrum.rightplane.planeEquation, transPosition);

    if (dist < -r)
    {
        return false;
    }
    
    dist = DistanceFromPlane(testFrustrum.leftplane.planeEquation, transPosition);

    if (dist < -r)
    {
        return false;
    }

    return true;
    
}

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

void main()
{
	uint index = (gl_WorkGroupID.x * gl_WorkGroupSize.x) + gl_LocalInvocationID.x;

    uint maxCount = gs.grid.indirectDrawCount;
  
    if (index >= maxCount)  
    {
        return;
    }

    MeshRenderable currentRenderable = rends.renderables[index];

    GeometryRenderable lGeomRenderable = geomRends.geomRenderables[currentRenderable.geomInstIndex];

    GeometryDetails lGeomDetails = geomDetails.details[lGeomRenderable.geomDescIndex];

    MeshDetails lModelData = perModelBuffer.objects[currentRenderable.meshIndex];

    mat4 worldM = lGeomRenderable.transform * currentRenderable.transform;

    vec4 sphere = lModelData.sphere;

    bool visible = CheckAllPlanesAgainstAABB(lGeomDetails.minMaxBox, worldM);

    if (!visible)
    {
        uint invisibleIndex = atomicAdd(cCounts.invisibleCount, 1u);
        cmdBuffer.commands[maxCount-(1+invisibleIndex)].instanceCount = 0;
        return;
    } 

    uint visibleIndex = atomicAdd(cCounts.visibleCount, 1u);
   
    imageStore(globalRenderableIndices, int(visibleIndex), uvec4(index, 0, 0, 0));

    cmdBuffer.commands[visibleIndex].instanceCount = currentRenderable.instanceCount;
    cmdBuffer.commands[visibleIndex].firstIndex = lModelData.firstIndex;
    cmdBuffer.commands[visibleIndex].indexCount = lModelData.indexCount;
    cmdBuffer.commands[visibleIndex].firstInstance = 0;
    cmdBuffer.commands[visibleIndex].vertexOffset = 0;
   
    return;
}
