#version 450

#include "include/Math.iglsl"
#include "include/Lights.iglsl"

struct UniformGrid
{
    vec4 max;
    vec4 min;
	uint numberOfDivisions;
    uint numberOfLights;
};

layout(push_constant) uniform GlobalContext 
{
    UniformGrid grid;
} gs;

layout(set = 0, binding = 0) buffer LightCounts 
{
	uint count[];
} lightCounts;

layout(set = 0, binding = 1) readonly buffer GLBuffer 
{
    LightSource objects[];
} lightBuffer;

layout(set = 0, binding = 2) buffer GridOffsets 
{
	uint offset[];
} gridOffsets;

layout(set = 0, binding = 3, r32ui) uniform uimageBuffer WorldAssignments;

layout(set = 0, binding = 4) buffer LightAssigns
{
	uint indices[];
} lightAssigns[LIGHT_TYPE_COUNT];

void HandleDirectionalLight(uint lIndex)
{
    for (uint x = 0; x<gs.grid.numberOfDivisions; x++)
    {
        for (uint y = 0; y<gs.grid.numberOfDivisions; y++)
        {
            for (uint z = 0; z<gs.grid.numberOfDivisions; z++)
            {
                uint insertIndex = (x * gs.grid.numberOfDivisions * gs.grid.numberOfDivisions) + (y * gs.grid.numberOfDivisions) + z;
                uint index = atomicAdd(gridOffsets.offset[insertIndex], 1u);
                imageStore(WorldAssignments, int(index), uvec4(lIndex, 0, 0, 0));
            }
        }
    }
}

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

void main()
{
	uint lIndex =  (gl_WorkGroupID.x * gl_WorkGroupSize.x) + gl_LocalInvocationID.x;

    if (lIndex >= lightCounts.count[LIGHT_TYPE_DIRECTIONAL]) return;

    uint lightIndex = lightAssigns[LIGHT_TYPE_DIRECTIONAL].indices[lIndex];
    
    HandleDirectionalLight(lightIndex);
   
	return;
}