#version 450

#extension GL_GOOGLE_include_directive: require

#include "include/Math.iglsl"
#include "include/Lights.iglsl"

struct UniformGrid
{
    vec4 max;
    vec4 min;
	uint numberOfDivisions;
    uint numberOfLights;
};

layout(push_constant) uniform GlobalContext 
{
    UniformGrid grid;
} gs;

layout(set = 0, binding = 0) buffer LightCounts 
{
	uint count[];
} lightCounts;

layout(set = 0, binding = 1) readonly buffer GLBuffer 
{
    LightSource objects[];
} lightBuffer;

layout(set = 0, binding = 2) buffer LightAssigns
{
	uint indices[];
} lightAssigns[LIGHT_TYPE_COUNT];

layout(set = 0, binding = 3) buffer GridOffsets 
{
	uint offset[];
} gridOffsets;

layout(set = 0, binding = 4, r32ui) uniform uimageBuffer WorldAssignments;

void HandlePointLightAssignment(uint lIndex)
{
    vec4 posLoad = lightBuffer.objects[lIndex].pos;

    vec3 AABBMin = clamp(posLoad.xyz - vec3(posLoad.w), gs.grid.min.xyz, gs.grid.max.xyz);
    vec3 AABBMax = clamp(posLoad.xyz + vec3(posLoad.w), gs.grid.min.xyz, gs.grid.max.xyz);
      
     if (any(lessThan(AABBMax, AABBMin)))
        return;

    vec4 range = gs.grid.max - gs.grid.min;
    vec3 cellDiv = range.xyz / float(gs.grid.numberOfDivisions);

    ivec3 cellsMin = ivec3(floor((AABBMin - gs.grid.min.xyz) / cellDiv));
    ivec3 cellsMax = ivec3(floor((AABBMax - gs.grid.min.xyz) / cellDiv));

    cellsMin = clamp(cellsMin, ivec3(0), ivec3(gs.grid.numberOfDivisions - 1));
    cellsMax = clamp(cellsMax, ivec3(0), ivec3(gs.grid.numberOfDivisions - 1));
    
    for (uint x = cellsMin.x; x<=cellsMax.x; x++)
    {
        for (uint y = cellsMin.y; y<=cellsMax.y; y++)
        {
            for (uint z = cellsMin.z; z<=cellsMax.z; z++)
            {
                vec3 gridMinPoints = (vec3(x, y, z) * cellDiv) + gs.grid.min.xyz;
                vec3 gridMaxPoints = gridMinPoints + cellDiv;

                if (SphereIntersectsAABB(posLoad.xyz, posLoad.w, gridMinPoints, gridMaxPoints)) 
                {
                    uint insertIndex = (x * gs.grid.numberOfDivisions * gs.grid.numberOfDivisions) + (y * gs.grid.numberOfDivisions) + z;
                    uint index = atomicAdd(gridOffsets.offset[insertIndex], 1u);
                    imageStore(WorldAssignments, int(index), uvec4(lIndex, 0, 0, 0));
                }  
            }
        }
    }
}

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

void main()
{
	uint lIndex =  (gl_WorkGroupID.x * gl_WorkGroupSize.x) + gl_LocalInvocationID.x;

    if (lIndex >= lightCounts.count[LIGHT_TYPE_POINT]) return;

    uint lightIndex = lightAssigns[LIGHT_TYPE_POINT].indices[lIndex];

    HandlePointLightAssignment(lightIndex);
  
	return;
}