#version 450

#extension GL_GOOGLE_include_directive: require

#include "include/Lights.iglsl"

struct UniformGrid
{
    vec4 max;
    vec4 min;
	uint numberOfDivisions;
    uint numberOfLights;
};

layout(push_constant) uniform GlobalContext 
{
    UniformGrid grid;
} gs;

layout(set = 0, binding = 0) readonly buffer LightCounts
{
	uint count[];
} lightCounts;

layout(set = 0, binding = 1) buffer GridCounts 
{
	uint count[];
} gridCounts;

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint localIndex = gl_LocalInvocationID.x;

    uint globalOffset = (gl_WorkGroupID.x * gl_WorkGroupSize.x);

	uint lIndex =  globalOffset + localIndex;

    if (lIndex < (gs.grid.numberOfDivisions*gs.grid.numberOfDivisions*gs.grid.numberOfDivisions))
    {
        atomicAdd(gridCounts.count[lIndex], lightCounts.count[LIGHT_TYPE_DIRECTIONAL] * LIGHT_TYPE_DIRECTIONAL_COUNT_MULTIPLIER);
    }
   
	return;
}