#version 450

#extension GL_GOOGLE_include_directive: require

#include "include/Math.iglsl"
#include "include/Lights.iglsl"

struct UniformGrid
{
    vec4 max;
    vec4 min;
	uint numberOfDivisions;
    uint numberOfLights;
};

layout(push_constant) uniform GlobalContext 
{
    UniformGrid grid;
} gs;

layout(set = 0, binding = 0) buffer Counts 
{
	int countsAtN[];
} counts;

layout(set = 0, binding = 1) readonly buffer GLBuffer 
{
    LightSource objects[];
} lightBuffer;

layout(set = 0, binding = 2) uniform usamplerBuffer globalLightTypes;

void HandlePointLightAssignment(uint lIndex)
{
    vec4 posLoad = lightBuffer.objects[lIndex].pos;
    vec3 posReal = posLoad.xyz;
    float r = posLoad.w;



    vec3 AABBMin = clamp(posReal - vec3(r), gs.grid.min.xyz, gs.grid.max.xyz);
    vec3 AABBMax = clamp(posReal + vec3(r), gs.grid.min.xyz, gs.grid.max.xyz);
      
     if (any(lessThan(AABBMax, AABBMin)))
        return;

    
    vec4 range = gs.grid.max - gs.grid.min;
    vec3 cellDiv = range.xyz / float(gs.grid.numberOfDivisions);

    ivec3 cellsMin = ivec3(floor((AABBMin - gs.grid.min.xyz) / cellDiv));
    ivec3 cellsMax = ivec3(floor((AABBMax - gs.grid.min.xyz) / cellDiv));

    cellsMin = clamp(cellsMin, ivec3(0), ivec3(gs.grid.numberOfDivisions - 1));
    cellsMax = clamp(cellsMax, ivec3(0), ivec3(gs.grid.numberOfDivisions - 1));
    
    for (uint x = cellsMin.x; x<=cellsMax.x; x++)
    {
        for (uint y = cellsMin.y; y<=cellsMax.y; y++)
        {
            for (uint z = cellsMin.z; z<=cellsMax.z; z++)
            {

                vec3 gridMinPoints = (vec3(x, y, z) * cellDiv) + gs.grid.min.xyz;
                vec3 gridMaxPoints = gridMinPoints + cellDiv;

                if (SphereIntersectsAABB(posReal, r, gridMinPoints, gridMaxPoints)) {
                    uint insertIndex = (x * gs.grid.numberOfDivisions * gs.grid.numberOfDivisions) + (y * gs.grid.numberOfDivisions) + z;
                    atomicAdd(counts.countsAtN[insertIndex], 1);
                }  
            }
        }
    }
}

void HandleDirectionalLight(uint lIndex)
{
    for (uint x = 0; x<gs.grid.numberOfDivisions; x++)
    {
        for (uint y = 0; y<gs.grid.numberOfDivisions; y++)
        {
            for (uint z = 0; z<gs.grid.numberOfDivisions; z++)
            {
                uint insertIndex = (x * gs.grid.numberOfDivisions * gs.grid.numberOfDivisions) + (y * gs.grid.numberOfDivisions) + z;
                atomicAdd(counts.countsAtN[insertIndex], 1);
            }
        }
    }

}

void HandleSpotLightAssignment(uint lIndex)
{
    vec4 posLoad = lightBuffer.objects[lIndex].pos;
    vec3 posReal = posLoad.xyz;
    float r = posLoad.w;
    vec3 lightDir = lightBuffer.objects[lIndex].direction.xyz;

    vec3 AABBStart = clamp(posReal, gs.grid.min.xyz, gs.grid.max.xyz);
    vec3 AABBStop = clamp(posReal + (lightDir * r), gs.grid.min.xyz, gs.grid.max.xyz);
      
    vec3 AABBMin = min(AABBStart, AABBStop);
    vec3 AABBMax = max(AABBStart, AABBStop);

    vec4 range = gs.grid.max - gs.grid.min;
    vec3 cellDiv = range.xyz / float(gs.grid.numberOfDivisions);

    ivec3 cellsMin = ivec3(floor((AABBMin - gs.grid.min.xyz) / cellDiv));
    ivec3 cellsMax = ivec3(floor((AABBMax - gs.grid.min.xyz) / cellDiv));

    cellsMin = clamp(cellsMin, ivec3(0), ivec3(gs.grid.numberOfDivisions - 1));
    cellsMax = clamp(cellsMax, ivec3(0), ivec3(gs.grid.numberOfDivisions - 1));
    
    for (uint x = cellsMin.x; x<=cellsMax.x; x++)
    {
        for (uint y = cellsMin.y; y<=cellsMax.y; y++)
        {
            for (uint z = cellsMin.z; z<=cellsMax.z; z++)
            {
                vec3 gridMinPoints = (vec3(x, y, z) * cellDiv) + gs.grid.min.xyz;
                vec3 gridMaxPoints = gridMinPoints + cellDiv;

                if (RayIntersectAABB(posReal, lightDir, gridMinPoints, gridMaxPoints, r)) {
                    uint insertIndex = (x * gs.grid.numberOfDivisions * gs.grid.numberOfDivisions) + (y * gs.grid.numberOfDivisions) + z;
                    atomicAdd(counts.countsAtN[insertIndex], 1);
                }  
            }
        }
    }
}

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

void main()
{

	uint lIndex =  (gl_WorkGroupID.x * gl_WorkGroupSize.x) + gl_LocalInvocationID.x;

    if (lIndex >= gs.grid.numberOfLights) return;

    uint lType = uint(texelFetch(globalLightTypes, int(lIndex)).r);
    
    if (lType == LIGHT_TYPE_DIRECTIONAL)
    {
        HandleDirectionalLight(lIndex);
    }
    else if (lType == LIGHT_TYPE_POINT)
    {
        HandlePointLightAssignment(lIndex);
    }
    else if (lType == LIGHT_TYPE_SPOT)
    {
       HandleSpotLightAssignment(lIndex);
    }
  
	return;
}