#version 450

#include "include/Math.iglsl"
#include "include/Lights.iglsl"

struct UniformGrid
{
    vec4 max;
    vec4 min;
	uint numberOfDivisions;
    uint numberOfLights;
};

layout(push_constant) uniform GlobalContext 
{
    UniformGrid grid;
} gs;

layout(set = 0, binding = 0) buffer LightCounts 
{
	uint count[];
} lightCounts;

layout(set = 0, binding = 1) readonly buffer GLBuffer 
{
    LightSource objects[];
} lightBuffer;

layout(set = 0, binding = 2) buffer GridOffsets 
{
	uint offset[];
} gridOffsets;

layout(set = 0, binding = 3, r32ui) uniform uimageBuffer WorldAssignments;

layout(set = 0, binding = 4) buffer LightAssigns
{
	uint indices[];
} lightAssigns[LIGHT_TYPE_COUNT];

layout(set = 0, binding = 5) buffer GridCounts 
{
	uint count[];
} gridCounts;

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

void main()
{
	uint lIndex =  (gl_WorkGroupID.x * gl_WorkGroupSize.x) + gl_LocalInvocationID.x;

    if (lIndex < (gs.grid.numberOfDivisions*gs.grid.numberOfDivisions*gs.grid.numberOfDivisions))
    {
        uint indexBase = gridOffsets.offset[lIndex];

        for (uint i = 0; i<lightCounts.count[LIGHT_TYPE_DIRECTIONAL]; i++)
        {
            uint lightIndex = lightAssigns[LIGHT_TYPE_DIRECTIONAL].indices[i];

            imageStore(WorldAssignments, int(indexBase +  i), uvec4(lightIndex, 0, 0, 0));
        }
    }
   
	return;
}