#version 450

#extension GL_GOOGLE_include_directive: require

#include "include/Math.iglsl"
#include "include/Lights.iglsl"

struct UniformGrid
{
    vec4 max;
    vec4 min;
	uint numberOfDivisions;
    uint numberOfLights;
};

layout(push_constant) uniform GlobalContext 
{
    UniformGrid grid;
} gs;

layout(set = 0, binding = 0) buffer LightCounts 
{
	uint count[];
} lightCounts;

layout(set = 0, binding = 1) readonly buffer GLBuffer 
{
    LightSource objects[];
} lightBuffer;

layout(set = 0, binding = 2) buffer LightAssigns 
{
	uint indices[];
} lightAssigns[LIGHT_TYPE_COUNT];

layout(set = 0, binding = 3) buffer GridCounts 
{
	uint count[];
} gridCounts;

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

void main()
{
	uint lIndex =  (gl_WorkGroupID.x * gl_WorkGroupSize.x) + gl_LocalInvocationID.x;

    uint x = lIndex / (gs.grid.numberOfDivisions*gs.grid.numberOfDivisions);
    uint y = (lIndex-(x*(gs.grid.numberOfDivisions*gs.grid.numberOfDivisions))) / (gs.grid.numberOfDivisions);
    uint z = lIndex % gs.grid.numberOfDivisions;

    vec4 range = gs.grid.max - gs.grid.min;
    vec3 cellDiv = range.xyz / float(gs.grid.numberOfDivisions);

    vec3 gridMinPoints = (vec3(x, y, z) * cellDiv) + gs.grid.min.xyz;
    vec3 gridMaxPoints = gridMinPoints + cellDiv;

    if (lIndex < (gs.grid.numberOfDivisions*gs.grid.numberOfDivisions*gs.grid.numberOfDivisions))
    {
        uint lightCounter = 0;

        for (uint i = 0; i<lightCounts.count[LIGHT_TYPE_SPOT]; i++)
        {
            uint lightIndex = lightAssigns[LIGHT_TYPE_SPOT].indices[i];

            vec4 posLoad = lightBuffer.objects[lightIndex].pos;
            vec3 posReal = posLoad.xyz;
            float r = posLoad.w;

            vec3 lightDir = lightBuffer.objects[lightIndex].direction.xyz;

            if (RayIntersectAABB(posReal, lightDir, gridMinPoints, gridMaxPoints, r)) 
            {
                lightCounter++;
            }
        }

        atomicAdd(gridCounts.count[lIndex], lightCounter * LIGHT_TYPE_SPOT_COUNT_MULTIPLIER);
    }
  
	return;
}