#version 450

#extension GL_GOOGLE_include_directive: require

#include "include/Math.iglsl"
#include "include/Mesh.iglsl"

struct UniformGrid
{
    vec4 max;
    vec4 min;
	uint numberOfDivisions;
    uint numberOfMeshes;
};

layout(push_constant) uniform GlobalContext 
{
    UniformGrid grid;
} gs;

layout(set = 0, binding = 0) buffer Counts 
{
	uint countsAtN[];
} counts;

layout(set = 0, binding = 1) readonly buffer PMBuffer 
{
    MeshDetails objects[];
} perModelBuffer;

layout(set = 0, binding = 2) buffer RENDBuffer
{
    MeshRenderable renderables[];
} rends;

layout(set = 0, binding = 3) readonly buffer GeomDescBuffer
{
    GeometryDetails details[];
} geomDetails;

layout(set = 0, binding = 4) readonly buffer GeomInstBuffer
{
    GeometryRenderable geomRenderables[];
} geomRends;

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

void main()
{
	uint lIndex =  (gl_WorkGroupID.x * gl_WorkGroupSize.x) + gl_LocalInvocationID.x;

    if (lIndex >= gs.grid.numberOfMeshes) 
        return;

    MeshRenderable currentRenderable = rends.renderables[lIndex];

    GeometryRenderable lGeomRenderable = geomRends.geomRenderables[currentRenderable.geomInstIndex];

    GeometryDetails lGeomDetails = geomDetails.details[lGeomRenderable.geomDescIndex];

    MeshDetails lModelData = perModelBuffer.objects[currentRenderable.meshIndex];

    mat4 worldM = lGeomRenderable.transform * currentRenderable.transform;

    AABB objBox = lGeomDetails.minMaxBox;

    AABB outObjTransform = TransformAABBArvo(worldM, objBox);

    vec4 transformMin = outObjTransform.min;
    vec4 transformMax = outObjTransform.max;

    vec4 AABBMin = min(transformMin, transformMax);
    vec4 AABBMax = max(transformMin, transformMax);

    vec3 clampedMin = max(AABBMin.xyz, gs.grid.min.xyz);
    vec3 clampedMax = min(AABBMax.xyz, gs.grid.max.xyz);

    if (any(lessThan(clampedMax, clampedMin)))
        return;
    
    vec4 range = gs.grid.max - gs.grid.min;
    vec3 cellDiv = range.xyz / float(gs.grid.numberOfDivisions);

    ivec3 cellsMin = ivec3(floor((clampedMin-gs.grid.min.xyz)/cellDiv ));
    ivec3 cellsMax = ivec3(floor((clampedMax-gs.grid.min.xyz)/cellDiv ));  

    cellsMin = clamp(cellsMin, ivec3(0), ivec3(gs.grid.numberOfDivisions - 1));
    cellsMax = clamp(cellsMax, ivec3(0), ivec3(gs.grid.numberOfDivisions - 1));

    for (uint x = cellsMin.x; x<=cellsMax.x; x++)
    {
        for (uint y = cellsMin.y; y<=cellsMax.y; y++)
        {
            for (uint z = cellsMin.z; z<=cellsMax.z; z++)
            {
                uint insertIndex = (x * gs.grid.numberOfDivisions * gs.grid.numberOfDivisions) + (y * gs.grid.numberOfDivisions) + z;
                atomicAdd(counts.countsAtN[insertIndex], 1u);
            }
        }
    }
    

	return;
}