#version 450

#extension GL_GOOGLE_include_directive: require

#include "include/Math.iglsl"
#include "include/Mesh.iglsl"

struct UniformGrid
{
    vec4 max;
    vec4 min;
	uint numberOfDivisions;
    uint numberOfMeshes;
};

layout(push_constant) uniform GlobalContext 
{
    UniformGrid grid;
} gs;

layout(set = 0, binding = 0) buffer Counts 
{
	uint countsAtN[];
} counts;

layout(set = 0, binding = 1) readonly buffer PMBuffer 
{
    MeshDetails objects[];
} perModelBuffer;

layout(set = 0, binding = 2) buffer RENDBuffer
{
    MeshRenderable renderables[];
} rends;

layout(set = 0, binding = 3) readonly buffer GeomDescBuffer
{
    GeometryDetails details[];
} geomDetails;

layout(set = 0, binding = 4) readonly buffer GeomInstBuffer
{
    GeometryRenderable geomRenderables[];
} geomRends;

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

void main()
{
	uint lIndex =  (gl_WorkGroupID.x * gl_WorkGroupSize.x) + gl_LocalInvocationID.x;

    uint x = lIndex / (gs.grid.numberOfDivisions*gs.grid.numberOfDivisions);
    uint y = (lIndex%(gs.grid.numberOfDivisions*gs.grid.numberOfDivisions)) / gs.grid.numberOfDivisions;
    uint z = lIndex % gs.grid.numberOfDivisions;

    vec4 range = gs.grid.max - gs.grid.min;
    vec3 cellDiv = range.xyz / float(gs.grid.numberOfDivisions);

    vec3 gridMinPoints = (vec3(x, y, z) * cellDiv) + gs.grid.min.xyz;
    vec3 gridMaxPoints = gridMinPoints + cellDiv;

    AABB gridAABB;

    gridAABB.min = vec4(gridMinPoints, 1.0);
    gridAABB.max = vec4(gridMaxPoints, 1.0);

    if (lIndex < (gs.grid.numberOfDivisions*gs.grid.numberOfDivisions*gs.grid.numberOfDivisions))
    {
        uint counter = 0;

        for (uint i = 0; i<gs.grid.numberOfMeshes; i++)
        {
            uint currentRenderableGeom = rends.renderables[i].geomInstIndex;

            GeometryRenderable lGeomRenderable = geomRends.geomRenderables[currentRenderableGeom];

            GeometryDetails lGeomDetails = geomDetails.details[lGeomRenderable.geomDescIndex];

            mat4 worldM = lGeomRenderable.transform * rends.renderables[i].transform;

            AABB objBox = lGeomDetails.minMaxBox;

            AABB outObjTransform = TransformAABBArvo(worldM, objBox);

            bool intersect = AABBIntersect(gridAABB, outObjTransform);

            if (intersect)
            {
                counter++;
            }   
        }

        counts.countsAtN[lIndex] = counter;
    }
    
	return;
}